### ISSUE TITLE
User friendly error message when no .repoman.json is found

### ISSUE THREAD

**Issue by basti1302** [basti1302/repoman#19]
Currently, when executing `repoman get`, `repoman changes` command in a directory that has no `.repoman.json`, you'll get something like this:

```
/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/node_modules/bagofcli/lib/bagofcli.js:429
    throw new Error('Unable to lookup file in ' + files.join(', '));
    ^

Error: Unable to lookup file in /home/bastian/codecentric/kunden/gea/.repoman.json, /home/bastian/.repoman.json
    at Object.lookupFile (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/node_modules/bagofcli/lib/bagofcli.js:429:11)
    at Command._exec (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/lib/cli.js:62:35)
    at Command.listener (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/node_modules/commander/index.js:615:12)
    at Command.parse (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/node_modules/commander/index.js:458:21)
    at Object.command (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/node_modules/bagofcli/lib/bagofcli.js:65:13)
    at Object.exec (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/lib/cli.js:143:7)
    at Object.<anonymous> (/home/bastian/.nvm/versions/node/v4.2.2/lib/node_modules/repoman/bin/repoman:4:5)
```

A nicer error message without stack trace would be good. Something along the lines of 

```
Could not find configuration file .repoman.json in the current directory. You can create a configuration file with repoman init or specify a different configuration file with -c. Use repoman --help or check https://github.com/basti1302/repoman/blob/master/README.md for more information.
```

**Comment by basti1302** [comment]
Fixed in release 1.1.0
