### ISSUE TITLE
TypeError with fresh install

### ISSUE THREAD

**Issue by xavdid** [basti1302/repoman#27]
repoman versoin: `1.5.3`
OS version: `macOS 10.12.6`
node: `8.9.4`

Hi there! I'm trying to set up config and am getting the following error: 

```bash
% repoman config --github-user cliffano
Setting configuration file: .repoman.json, with GitHub repositories
Unhandled rejection TypeError: self.gh.repos.getFromUser is not a function
    at /Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/lib/generator/github.js:79:21
    at /Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/async/dist/async.js:3866:24
    at replenish (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/async/dist/async.js:998:17)
    at /Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/async/dist/async.js:1002:9
    at _parallel (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit$1 [as parallelLimit] (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/async/dist/async.js:3971:5)
    at GitHub.generate (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/lib/generator/github.js:112:9)
    at /Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/lib/repoman.js:66:14
    at error (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/lib/generator/github.js:56:9)
    at tryCatcher (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/david/.nvm/versions/node/v8.9.4/lib/node_modules/repoman/node_modules/bluebird/js/release/async.js:143:10)
```

Out of curiosity, I downgraded to `1.3.1` and it's working as expected!

**Comment by basti1302** [comment]
Thanks for the report! This has been fixed in 1.5.4.
