### ISSUE TITLE
repoman config --local crashes with TypeError

### ISSUE THREAD

**Issue by skagedal** [basti1302/repoman#30]
```
$ npm install -g repoman
/usr/local/bin/repoman -> /usr/local/lib/node_modules/repoman/bin/repoman
+ repoman@1.5.5
added 535 packages from 975 contributors in 26.566s
$ rehash
$ cd code
$ repoman config --local
Setting configuration file: .repoman.json, with local repositories
/usr/local/lib/node_modules/repoman/lib/generator/local.js:49
  var url  = info['remote "origin"'].url;
                                     ^

TypeError: Cannot read property 'url' of undefined
    at Local._git (/usr/local/lib/node_modules/repoman/lib/generator/local.js:49:38)
    at /usr/local/lib/node_modules/repoman/lib/generator/local.js:35:12
    at Array.forEach (<anonymous>)
    at Local.generate (/usr/local/lib/node_modules/repoman/lib/generator/local.js:29:9)
    at Repoman.config (/usr/local/lib/node_modules/repoman/lib/repoman.js:82:11)
    at Command._config (/usr/local/lib/node_modules/repoman/lib/cli.js:48:17)
    at Command.listener (/usr/local/lib/node_modules/repoman/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (/usr/local/lib/node_modules/repoman/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/repoman/node_modules/commander/index.js:474:21)
    at Object.command (/usr/local/lib/node_modules/repoman/node_modules/bagofcli/lib/bagofcli.js:65:13)
    at Object.exec (/usr/local/lib/node_modules/repoman/lib/cli.js:217:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/repoman/bin/repoman:4:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
➜  code
```

* `code` is a directory that contains git repositories. (but also perhaps some directories that aren't git repos; is that the problem?)
* Running on macOS Catalina

**Comment by skagedal** [comment]
> (but also perhaps some directories that aren't git repos; is that the problem?)

No, I tried moving non-git directories out of `code` and still got same problem.

**Comment by skagedal** [comment]
Ah, but there was one repo that did not have an origin. That's the problem. Would be nice if `repoman` just ignored that.

**Comment by basti1302** [comment]
PR welcome :-)

**Comment by skagedal** [comment]
Nixe, thanks @basti1302!
