### ISSUE TITLE
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by stennie** [basti1302/repoman#55]
Running `repoman config --local` for a fresh install of `repoman` 1.6.0 on Node 20.9.0 reports:
```
Creating sample configuration file: .repoman.json
(node:5355) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:815:11)
    at Object.get (node:internal/modules/cjs/loader:831:5)
    at exports.setLevels (.../repoman/node_modules/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (.../repoman/node_modules/winston/lib/winston.js:84:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
```
The `.repoman.json` file still appears to be created correctly

**Comment by basti1302** [comment]
Yes, I've seen these for quite a while, not only on Node 20. I never found the time to look into this.

**Comment by basti1302** [comment]
Looks like https://github.com/basti1302/repoman/pull/59 has taken care of this as well. I can no longer reproduce this on the `main` branch.
